DB_SERVER_HOST = "localhost"
DB_SERVER_PORT = "5432"
DB_DATABASE_NAME = "RocketQA"
DB_USER = "postgres"
DB_PW = "lhc20020716"
LANGUAGE = "zh"
SERVICE_NAME = "index_data"
SERVICE_PATH = "/opt/hanxc_20220411/pyRocketQA/"
SERVICE_PORT = "8889"
SERVICE_HOST = "localhost"
SERVICE_SUB_ADDRESS = r"/rocketqa"
TABLE_NAME = "m_info"
TOPK = 5
PROBABILITY =0.0005
RESTART_SERVICE_PROCESS = "pid_file"

